### PR TITLE
Added the save customer method to ruby api

### PR DESCRIPTION
**Pull request by brocktimus**
As per discussions in #3.

### CODE REVIEW

**Comment by brocktimus** [comment]
BTW at least the initial bits of this for me are working. Hunting down that the token_customer_id wasn't flowing through `Response -> InternalTransaction -> Transaction` properly took a bit of time. Unsure if all the attributes should just be copied, but just adding the one was enough for my purposes.

**Comment by incarnate** [comment]
Thanks for the updates @brocktimus - let me know when you are happy and I'll see if I can sort out the broken tests.

**Comment by brocktimus** [comment]
Yep this seems to be working for us. Not sure if you wanted to expose all the attributes from the internal transaction onto the resulting transaction object. Just the `token_customer_id` is enough for my use case.

**Comment by brocktimus** [comment]
@incarnate got this running on production and it's working a treat. Only bit that's untested yet is if this same code works when we're trying to update a customers token and perform a transaction on a shared responsive page at the same time.

**Pull request merged**
